### ISSUE TITLE
Use external template

### ISSUE THREAD

**Issue by adaniello** [EFTEC/AMPGeneratorOne#1]
Hi, i think that is more efficient and useful remove template as method's variable and use an external file.
What do you think about?
Thanks

**Comment by jorgecc** [comment]
Hi:
I really thought about it but I rejected the idea because of performance issue and to keep the library as simple (one file, no dependency).  **The code is ugly** but **it works and it is able to maintain and to extend**.  So it is more a matter of aesthetic of the code.   As for expansion, since this library is simple, it is possible to expand it and add new methods or send raw information.   Also, the ideology of AMP is not the customization, most AMP sites (CNN, FOX, BBC and such) are the same with different colors, even their menus are simple if not ugly.   AMP is more minimalist, so it doesn't justify more customization, i.e. AMP is only to fulfill Google requirement (i prefer to use Bootstrap).   So this library is not about customization but to do a fast job.
Also, it is not a template system, I have another library for that https://github.com/EFTEC/BladeOne
